### PR TITLE
Add closing } for the class HomePage in example snippet

### PR DESCRIPTION
**Pull request by mann-codes2014**
Closing **}** was missing for  class **HomePage** in section https://capacitorjs.com/docs/guides/push-notifications-firebase#using-the-capacitor-push-notification-api

### CODE REVIEW

**Comment by mann-codes2014** [comment]
Hi @clouder @nbennke . I am doing my first contribution, if this is fine. Otherwise let me know, so I can close this

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
Thanks for the PR.

Can you indent the `ngOnInit` line like in https://github.com/ionic-team/capacitor-docs/blob/main/docs/main/guides/push-notifications-firebase.md?plain=1#L167 
and the `}` on top the one you added like https://github.com/ionic-team/capacitor-docs/blob/main/docs/main/guides/push-notifications-firebase.md?plain=1#L203?

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
Sorry if it wasn't clear, but I meant only the `ngOnInit() {` line, the other code was already indented using 2 spaces and now is using 4, can you change it to 2?

**Comment by mann-codes2014** [comment]
> Sorry if it wasn't clear, but I meant only the `ngOnInit() {` line, the other code was already indented using 2 spaces and now is using 4, can you change it to 2?

sure

**Review by jcesarmobile — APPROVED** [review]

**Comment by jcesarmobile** [comment]
thanks!

**Pull request merged**
